spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/FinalProject
    username: postgres
    password: Na260206
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
